In [6]:
import re
from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
import pandas as pd

In [7]:
import googlesearch

In [8]:
def checkAWSRankings(url):
    try:
        lnk = 'https://www.alexa.com/siteinfo/'+url
        rc = BeautifulSoup(urlopen(lnk), 'html.parser')
        val = (rc.find('strong', class_= 'metrics-data align-vmiddle').text)
    except:
        val = "E"
    print(val)
    return val

In [15]:
def checkSubdomains(domain):

    return len(domain.split('.'))

In [16]:
data_df = pd.read_csv('dataset.csv',header= None)

In [17]:
data_df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,https://locking-app-adverds.000webhostapp.com/...,1,-1,-1,1,1,-1,-1,-1,-1,yes
1,https://mxtoolbox.com/public/upgradev2.aspx?ps...,0,-1,-1,-1,-1,-1,-1,-1,-1,no
2,http://parolishop.com.br/questionreviews.htm,0,-1,-1,-1,-1,-1,-1,-1,-1,yes
3,http://innovate.ieee.org/innovate/35675?lt=xpl...,1,-1,-1,-1,-1,-1,-1,-1,-1,no
4,http://ietbhaddal.edu.in/bb.mobile/mobile/inde...,0,-1,-1,-1,-1,-1,1,-1,-1,yes

In [18]:
url_names_arr = data_df[0].tolist()

In [34]:

dots = (list(map(checkSubdomains, url_names_arr)))

In [35]:
dots_df = pd.DataFrame(dots,columns=['SubDomains'])

In [36]:
dots_df.head()

   SubDomains
0           4
1           8
2           4
3           4
4           5

In [37]:
data_df = pd.concat([data_df, dots_df],axis=1, ignore_index=True)

In [38]:
data_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,https://locking-app-adverds.000webhostapp.com/...,1,-1,-1,1,1,-1,-1,-1,-1,yes,4
1,https://mxtoolbox.com/public/upgradev2.aspx?ps...,0,-1,-1,-1,-1,-1,-1,-1,-1,no,8
2,http://parolishop.com.br/questionreviews.htm,0,-1,-1,-1,-1,-1,-1,-1,-1,yes,4
3,http://innovate.ieee.org/innovate/35675?lt=xpl...,1,-1,-1,-1,-1,-1,-1,-1,-1,no,4
4,http://ietbhaddal.edu.in/bb.mobile/mobile/inde...,0,-1,-1,-1,-1,-1,1,-1,-1,yes,5